/* The following code was generated by JFlex 1.6.1 */

/*
Autores:      Cabrera Gaytán Jazmín Andrea
              Camacho Morales Gerardo Iván
              Nicolas Marin Brian Geovanny
              Lázaro Martínez Abraham Josué
              Oropeza Castañeda Ángel Eduardo

Versión:      1.1
Fecha:        18 de enero de 2021
Nombre:       lexer.jflex
*/
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lexer.jflex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\60\1\61\1\62\1\62\1\60\22\0\1\60\1\30\1\53"+
    "\2\0\1\37\1\27\1\51\1\44\1\45\1\35\1\33\1\50\1\34"+
    "\1\57\1\36\12\2\1\46\1\47\1\31\1\25\1\32\2\0\4\1"+
    "\1\56\17\1\1\54\5\1\1\42\1\52\1\43\1\0\1\55\1\0"+
    "\1\11\1\17\1\12\1\15\1\20\1\6\1\1\1\13\1\3\1\1"+
    "\1\24\1\7\1\1\1\4\1\10\2\1\1\14\1\22\1\5\1\16"+
    "\1\21\1\23\1\54\2\1\1\40\1\26\1\41\7\0\1\62\u1fa2\0"+
    "\1\62\1\62\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\13\2\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\3\1\1\26\1\27\2\0\1\30\1\2\1\31\7\2"+
    "\1\32\6\2\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\0\1\41\3\0\1\30\1\0\1\42\16\2\1\43"+
    "\1\2\1\44\1\45\1\46\4\2\1\47\1\50\2\2"+
    "\1\51\3\2\1\52\1\2\1\53\1\54\1\55\1\2"+
    "\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\u0132\0\u0165"+
    "\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd"+
    "\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\u042f\0\u0462\0\u0495\0\63\0\63"+
    "\0\u04c8\0\u04fb\0\u052e\0\u0561\0\146\0\u0594\0\u05c7\0\u05fa"+
    "\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792"+
    "\0\u07c5\0\u07f8\0\u082b\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\u042f\0\63\0\u085e\0\u0462\0\u0891\0\u08c4\0\u08f7"+
    "\0\146\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c"+
    "\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\146"+
    "\0\u0bf4\0\146\0\146\0\146\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0"+
    "\0\146\0\146\0\u0cf3\0\u0d26\0\146\0\u0d59\0\u0d8c\0\u0dbf"+
    "\0\146\0\u0df2\0\146\0\146\0\146\0\u0e25\0\146\0\146";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\3\3"+
    "\1\10\1\3\1\11\1\12\1\3\1\13\1\14\1\15"+
    "\1\16\1\17\1\3\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\2\1\45\3\3\1\46\1\47\1\50\65\0\24\3"+
    "\27\0\3\3\6\0\1\4\15\0\1\51\34\0\1\52"+
    "\1\51\1\53\4\0\3\3\1\54\1\3\1\55\16\3"+
    "\27\0\3\3\5\0\13\3\1\56\10\3\27\0\3\3"+
    "\5\0\6\3\1\57\1\3\1\60\4\3\1\61\6\3"+
    "\27\0\3\3\5\0\10\3\1\62\1\3\1\63\11\3"+
    "\27\0\3\3\5\0\17\3\1\64\4\3\27\0\3\3"+
    "\5\0\7\3\1\65\7\3\1\66\4\3\27\0\3\3"+
    "\5\0\13\3\1\67\10\3\27\0\3\3\5\0\6\3"+
    "\1\70\15\3\27\0\3\3\5\0\7\3\1\71\14\3"+
    "\27\0\3\3\5\0\22\3\1\72\1\3\27\0\3\3"+
    "\5\0\12\3\1\73\11\3\27\0\3\3\31\0\1\74"+
    "\63\0\1\75\63\0\1\76\60\0\1\77\62\0\1\100"+
    "\62\0\1\101\35\0\51\102\1\103\1\104\10\102\52\105"+
    "\1\106\1\103\7\105\2\0\1\53\62\0\1\107\30\0"+
    "\2\110\30\0\1\4\62\0\1\53\15\0\1\51\35\0"+
    "\1\51\5\0\4\3\1\111\17\3\27\0\3\3\5\0"+
    "\15\3\1\112\6\3\27\0\3\3\5\0\7\3\1\113"+
    "\14\3\27\0\3\3\5\0\6\3\1\114\15\3\27\0"+
    "\3\3\5\0\3\3\1\115\20\3\27\0\3\3\5\0"+
    "\21\3\1\116\2\3\27\0\3\3\5\0\10\3\1\117"+
    "\13\3\27\0\3\3\5\0\4\3\1\120\17\3\27\0"+
    "\3\3\5\0\15\3\1\121\6\3\27\0\3\3\5\0"+
    "\5\3\1\122\16\3\27\0\3\3\5\0\17\3\1\123"+
    "\4\3\27\0\3\3\5\0\21\3\1\124\2\3\27\0"+
    "\3\3\5\0\2\3\1\125\21\3\27\0\3\3\5\0"+
    "\2\3\1\126\21\3\27\0\3\3\5\0\2\3\1\127"+
    "\21\3\27\0\3\3\10\0\1\102\11\0\1\102\32\0"+
    "\4\102\12\0\1\105\11\0\1\105\32\0\4\105\10\0"+
    "\1\107\52\0\1\110\7\0\1\107\61\0\17\3\1\130"+
    "\4\3\27\0\3\3\5\0\10\3\1\131\13\3\27\0"+
    "\3\3\5\0\21\3\1\112\2\3\27\0\3\3\5\0"+
    "\11\3\1\132\12\3\27\0\3\3\5\0\17\3\1\133"+
    "\4\3\27\0\3\3\5\0\13\3\1\134\10\3\27\0"+
    "\3\3\5\0\15\3\1\135\6\3\27\0\3\3\5\0"+
    "\16\3\1\136\5\3\27\0\3\3\5\0\10\3\1\137"+
    "\13\3\27\0\3\3\5\0\10\3\1\140\13\3\27\0"+
    "\3\3\5\0\17\3\1\141\4\3\27\0\3\3\5\0"+
    "\14\3\1\142\7\3\27\0\3\3\5\0\4\3\1\143"+
    "\17\3\27\0\3\3\5\0\6\3\1\144\15\3\27\0"+
    "\3\3\5\0\4\3\1\145\17\3\27\0\3\3\5\0"+
    "\13\3\1\146\10\3\27\0\3\3\5\0\6\3\1\147"+
    "\15\3\27\0\3\3\5\0\15\3\1\150\6\3\27\0"+
    "\3\3\5\0\23\3\1\151\27\0\3\3\5\0\11\3"+
    "\1\152\12\3\27\0\3\3\5\0\17\3\1\153\4\3"+
    "\27\0\3\3\5\0\3\3\1\154\20\3\27\0\3\3"+
    "\5\0\17\3\1\155\4\3\27\0\3\3\5\0\6\3"+
    "\1\156\15\3\27\0\3\3\5\0\12\3\1\157\11\3"+
    "\27\0\3\3\5\0\4\3\1\160\17\3\27\0\3\3"+
    "\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3672];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\23\1\16\11\3\1\2\11\2\0\21\1"+
    "\6\11\1\0\1\11\3\0\1\1\1\0\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
//Definición de constantes para definir que número regresará el 
//analizador para cada token
//TIPOS DE DATOS
private static final int INT=1;
private static final int FLOAT=2;
private static final int CHAR=3;
private static final int DOUBLE=4;
private static final int VOID=5;
//PALABRAS RESERVADAS
private static final int FUNC=6;
private static final int IF=7;
private static final int ELSE=8;
private static final int WHILE=9;
private static final int DO=10;
private static final int BREAK=11;
private static final int SWITCH=12;
private static final int CASE=13;
private static final int DEFAULT=14;
private static final int RETURN=45;
//OPERADORES
private static final int ASIGNACION=15;
private static final int OR=16;
private static final int AND=17;
private static final int IGUAL=18;
private static final int DESIGUAL=19;
private static final int LT=20;
private static final int LET=21;
private static final int MT=22;
private static final int MET=23;
private static final int SUMA=24;
private static final int RESTA=25;
private static final int MULTI=26;
private static final int DIVISION=27;
private static final int MODULO=28;
private static final int NEGACION=29;
//PUNTUACION
private static final int L1=30;
private static final int L2=31;
private static final int C1=32;
private static final int C2=33;
private static final int P1=34;
private static final int P2=35;
private static final int DOSPUNTOS=36;
private static final int PUNTOYCOMA=37;
private static final int COMA=38;
//LITERALES
private static final int IDENTIFIER=39;
private static final int STRING_LIT=40;
private static final int TRUE=41;
private static final int FALSE=42;
private static final int INT_LIT=43;
private static final int FLOAT_LIT=44;

public String linea = "";

public int getYyline(){
  return this.yyline;
}

public void anexar(){
  linea+=yytext();
}

public void limpiar(){
  linea = "";
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   //Al encontrar el fin de archivo, regresa un valor 0
  return 0;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { anexar();return -1;
            }
          case 48: break;
          case 2: 
            { anexar();return IDENTIFIER;
            }
          case 49: break;
          case 3: 
            { anexar();return INT_LIT;
            }
          case 50: break;
          case 4: 
            { anexar();return ASIGNACION;
            }
          case 51: break;
          case 5: 
            { anexar();return NEGACION;
            }
          case 52: break;
          case 6: 
            { anexar();return LT;
            }
          case 53: break;
          case 7: 
            { anexar();return MT;
            }
          case 54: break;
          case 8: 
            { anexar();return SUMA;
            }
          case 55: break;
          case 9: 
            { anexar();return RESTA;
            }
          case 56: break;
          case 10: 
            { anexar();return MULTI;
            }
          case 57: break;
          case 11: 
            { anexar();return DIVISION;
            }
          case 58: break;
          case 12: 
            { anexar();return MODULO;
            }
          case 59: break;
          case 13: 
            { anexar();return L1;
            }
          case 60: break;
          case 14: 
            { anexar();return L2;
            }
          case 61: break;
          case 15: 
            { anexar();return C1;
            }
          case 62: break;
          case 16: 
            { anexar();return C2;
            }
          case 63: break;
          case 17: 
            { anexar();return P1;
            }
          case 64: break;
          case 18: 
            { anexar();return P2;
            }
          case 65: break;
          case 19: 
            { anexar();return DOSPUNTOS;
            }
          case 66: break;
          case 20: 
            { anexar();return PUNTOYCOMA;
            }
          case 67: break;
          case 21: 
            { anexar();return COMA;
            }
          case 68: break;
          case 22: 
            { /*No se hace nada*/
            }
          case 69: break;
          case 23: 
            { limpiar();
            }
          case 70: break;
          case 24: 
            { anexar();return FLOAT_LIT;
            }
          case 71: break;
          case 25: 
            { anexar();return IF;
            }
          case 72: break;
          case 26: 
            { anexar();return DO;
            }
          case 73: break;
          case 27: 
            { anexar();return IGUAL;
            }
          case 74: break;
          case 28: 
            { anexar();return OR;
            }
          case 75: break;
          case 29: 
            { anexar();return AND;
            }
          case 76: break;
          case 30: 
            { anexar();return DESIGUAL;
            }
          case 77: break;
          case 31: 
            { anexar();return LET;
            }
          case 78: break;
          case 32: 
            { anexar();return MET;
            }
          case 79: break;
          case 33: 
            { anexar();return STRING_LIT;
            }
          case 80: break;
          case 34: 
            { anexar();return INT;
            }
          case 81: break;
          case 35: 
            { anexar();return TRUE;
            }
          case 82: break;
          case 36: 
            { anexar();return FUNC;
            }
          case 83: break;
          case 37: 
            { anexar();return CASE;
            }
          case 84: break;
          case 38: 
            { anexar();return CHAR;
            }
          case 85: break;
          case 39: 
            { anexar();return ELSE;
            }
          case 86: break;
          case 40: 
            { anexar();return VOID;
            }
          case 87: break;
          case 41: 
            { anexar();return FLOAT;
            }
          case 88: break;
          case 42: 
            { anexar();return BREAK;
            }
          case 89: break;
          case 43: 
            { anexar();return WHILE;
            }
          case 90: break;
          case 44: 
            { anexar();return RETURN;
            }
          case 91: break;
          case 45: 
            { anexar();return DOUBLE;
            }
          case 92: break;
          case 46: 
            { anexar();return SWITCH;
            }
          case 93: break;
          case 47: 
            { anexar();return DEFAULT;
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
